version: '2'

services:

  postgres:
    image: 'postgres:10.3-alpine'
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=urlshortener
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  app:
    build: ./src
    image: 'jaraindawn.azurecr.io/url-shortener_app:latest'
    ports:
      - '80:80'
    links:
      - postgres:postgres
      - elasticsearch:elasticsearch

volumes:
  pgdata: {}
  esdata: {}
